### PR TITLE
Skips JavaScript import if on FastBoot

### PR DESCRIPTION
**Pull request by locks**

### CODE REVIEW

**Comment by sir-dunxalot** [comment]
I don't have any experience with fast boot but it looks like this will only import the vendor file if the app is running in fast book, no? Isn't that the opposite of what we want?

**Comment by locks** [comment]
You are most correct, I forgot the negation operator! I'll update on a short while.

**Comment by locks** [comment]
There we go. Can you squash through the GitHub interface?

**Comment by sir-dunxalot** [comment]
Great, thanks. And yep - I'll squash in Github.

**Pull request merged**
