### PR TITLE
a15n/ updates and add svgs

### PR DESCRIPTION
**Pull request by a15n**
* adds `?branch=master` to the README's "Build Status" source
* adds `?branch=master` to the demo app's template's "Build Status"  tag
* adds Ember Observer score to README and demo app's template

screen shot 2017-01-31 at 10 48 43 am

screen shot 2017-01-31 at 10 53 16 am

### CODE REVIEW

**Comment by a15n** [comment]
We should probably also add the ember-observer score to the dummy app. What is the process for creating the `src` from the `data-canonical-src`?

**Comment by sir-dunxalot** [comment]
Not sure about the `data-canonical-src` - does your questions still apply?

**Comment by sir-dunxalot** [comment]
Fixes #161

**Comment by a15n** [comment]
I just don't know what `canonical-data-src` is or if we should update it....

Not a blocking question though

**Comment by a15n** [comment]
just ran `ember try:each` locally and not all tests are passing. Hold off on merging for now

**Comment by sir-dunxalot** [comment]
I don't know what `data-canonical-src` is either - I don't see it referenced in Travis' copy and paste badge modal.

Will hold off merging until you give the go ahead but I expect #177 will make the test suite pass for this PR.

**Comment by a15n** [comment]
Tests passed. I'm going to merge now

**Pull request merged**
