### PR TITLE
Bug fix for tooltips on link-to components not disappearing.

### PR DESCRIPTION
**Pull request by pauc**

### CODE REVIEW

**Comment by sir-dunxalot** [comment]
Pau, you're a lifesaver! This bug has been an issue for a while. I will pull down, test it out, and merge ASAP.

**Comment by sir-dunxalot** [comment]
Fixes #24 (again).

**Comment by pauc** [comment]
I added some test but they are not really useful, because I couldn't get a fail before apply the fix, so it was a green to green...

**Comment by sir-dunxalot** [comment]
Ok. I'll see if I can cause a failing test on master branch before merging this.

**Comment by pauc** [comment]
I think part of the problem is caused by this lines: https://github.com/sir-dunxalot/ember-tooltips/blob/0a8842e957f1361c1e64c707d084e588a0f4b8b6/addon/utils/render-tooltip.js#L194 and the 'debounce' on line 39. The 'focusin' event is fired alongside with the 'click' event, and this line https://github.com/sir-dunxalot/ember-tooltips/blob/0a8842e957f1361c1e64c707d084e588a0f4b8b6/addon/utils/render-tooltip.js#L56 gets executed when the component with the tooltip is on the "isDestroying" state and the transition to the new route already took place.

I created a brach with some debug statements to try to see what happens: https://github.com/pauc/ember-tooltips/tree/debug.

I really can't figure out how to reproduce the bug in acceptance tests...

Hey, and thanks for the addon :-) !!

**Comment by sir-dunxalot** [comment]
I think I have a failing acceptance test. I also have a reproducible bug for manual testing. I will go ahead and merge this to see what happens.

**Comment by sir-dunxalot** [comment]
The failing test didn't pass when this was merged but the reproducible bug has been fixed. We at least have *some* test coverage against transitions. My worry is the bug is rooted in something not reproducible calling `click()` in the JS but, instead, must be triggered by a user clicking in the browser.

However, I've done a lot of digging without much progress and this PR fixes the issue. I will release shortly because this bug is affecting many people. I will also create an issue for not having a failing test for the bug fixed by this PR.

**Comment by sir-dunxalot** [comment]
cc @cmcn

**Comment by iezer** [comment]
Does using `tooltip-for-component` inside a `link-to` work? I can't get it to work and I'm using ember-tooltips 2.5.0 and ember 2.7.3. Also is the `tooltipContent` property deprecated?

**Pull request merged**
