### PR TITLE
added display delay option

### PR DESCRIPTION
**Pull request by bekzod**
I needed this for my own use-case, is it worth merging ?

### CODE REVIEW

**Comment by sir-dunxalot** [comment]
Hey, thanks for the PR!

So the use case here is you want to show a tooltip when someone (let's say) hovers over a button but you only want to show the tooltip after five seconds?

And in that situation, what would happen is you stopped hovering before the tooltip is shown? Would the tooltip be cancelled?

**Comment by bekzod** [comment]
yes I want to show it delayed few seconds (1 second actually),

and yes it should be canceled

**Comment by sir-dunxalot** [comment]
Ok. This idea has been mentioned before and I think it would be a good feature add.

Before this is merged can you add a test to cover this new `delay` option?

I can take care of the documentation before we release it.

**Comment by bekzod** [comment]
Cool, ok will try cover it with tests, thanks

**Comment by lepolt** [comment]
This is a feature that we would like to use as well... but I noticed the request for tests was not completed. If I add the tests, do you think this PR could get merged?

**Comment by bekzod** [comment]
sorry I haven't had chance to add tests for this, @lepolt it would be great if you could added test for this thanks

**Comment by lepolt** [comment]
@bekzod I submitted a PR with tests in your repo... https://github.com/bekzod/ember-tooltips/pull/1

**Comment by bekzod** [comment]
@lepolt thanks, it is merged

**Comment by sir-dunxalot** [comment]
Good work all! This is now merged onto master. I will make a release as soon as I can (probably later this week) but the master is useable in your `package.json` files in the interim.

Let me know if that doesn't work for you.

**Comment by lepolt** [comment]
@sir-dunxalot did you forget to push? master doesn't look like it has the PR merged in...

**Comment by bekzod** [comment]
@sir-dunxalot I think you forgot to push/merge it

**Comment by sir-dunxalot** [comment]
Sorry everyone! It's merged now.

**Pull request merged**
