### PR TITLE
Fix issue with Fastboot

### PR DESCRIPTION
**Pull request by aexmachina**

### CODE REVIEW

**Comment by aexmachina** [comment]
Fixes #129

**Comment by aexmachina** [comment]
Fixes #130

**Comment by aexmachina** [comment]
See [comments](https://github.com/sir-dunxalot/ember-tooltips/issues/130#issuecomment-267428862) on #130

**Comment by a15n** [comment]
since we don't have any tests protecting this can you add comments above your code changes to ensure people don't delete the code without realizing it's purpose?  Then this LGTM if @sir-dunxalot agrees.

Thanks for doing this.

**Comment by aexmachina** [comment]
Okay @a15n, have done. No worries!

**Comment by sir-dunxalot** [comment]
Looks good! Will merge into master now.

**Pull request merged**
