### PR TITLE
Event refactoring

### PR DESCRIPTION
**Pull request by sir-dunxalot**
Fixes some issues, improves documentation, and adds `hideOn` and `showOn`.

### CODE REVIEW

**Comment by eduardbaitinger** [comment]
Commit b248595 adds tooltip content also to the title attribute and enables the browser tooltip.
This leads to duplicated tooltips and can be very ugly when a tooltip contains html-markup, which is also displayed in the native browser tooltip.

**Comment by sir-dunxalot** [comment]
Agreed. This was a regression. I will add an issue not we keep track of that.

**Comment by sir-dunxalot** [comment]
See #38

**Comment by eduardbaitinger** [comment]
Ok, thank you for the quick response.

**Pull request merged**
