### PR TITLE
Support `SafeString` in `tooltipContent`

### LINKED ISSUE #29: tooltipContent can't handle safeString
I'm setting tooltipContent from the translation object (ember-i18n) which returns an SafeString object with the string property, which contains the actual message. 

As a result from the tooltip I get an error message: Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'. tooltip/index.js:225

### PR DESCRIPTION
**Pull request by joukevandermaas**
Fixes #29

### CODE REVIEW

**Comment by joukevandermaas** [comment]
@sir-dunxalot CI is failing because of a jscs update that includes previously custom rules from ember suave. The fix is to update ember suave to version 1.2.3, but I'm not sure if I should do so in the context of this PR.

**Comment by sir-dunxalot** [comment]
This looks great! And, yes, please update the dependency if that will resolve the test suite. Once it's passing I'll merge, pull down, and release.

Do you know of a way to test the SafeString regression doesn't occur again?

**Comment by joukevandermaas** [comment]
@sir-dunxalot I added a test for this to prevent regressions (and squashed the commits).

However, it appears [something broke](https://travis-ci.org/sir-dunxalot/ember-tooltips/jobs/95824460#L417) with the Ember beta test scenario. I don't have time to look into it today, but it doesn't look like it's related to this PR.

**Comment by sir-dunxalot** [comment]
Ok, no worries. Overall, this is awesome - thanks for the test. I will merge into master and dig into the beta/canary issue now.

**Comment by joukevandermaas** [comment]
Awesome, thanks!

**Comment by sir-dunxalot** [comment]
Released as 0.5.5.

**Pull request merged**
